name: Build All

on:
  push:
    branches: [stable, dev]
    tags: 
      - "*"
  pull_request:
    branches: [stable, dev]

jobs:
  buildDeb:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files from repository to workspace
        uses: actions/checkout@v6
      - name: Fetch metadata
        run: |
          fetchMetadataValue() {
            curl -s https://raw.githubusercontent.com/shaweel/shaweelTimer/refs/heads/${{ github.ref_name }}/metadata.json \
            | grep -o "\"$1\": *\"[^\"]*\"" \
            | sed 's/.*: *"\(.*\)"/\1/'
          }
          echo "PACKAGE_NAME=$(fetchMetadataValue "packageName")" >> $GITHUB_ENV
          echo "DESCRIPTION=$(fetchMetadataValue "description")" >> $GITHUB_ENV
          echo "VERSION=$(fetchMetadataValue "version")" >> $GITHUB_ENV
          echo "URL=$(fetchMetadataValue "url")" >> $GITHUB_ENV
          echo "MAINTAINER=$(fetchMetadataValue "maintainer")" >> $GITHUB_ENV
          echo "MAINTAINER_EMAIL=$(fetchMetadataValue "maintainerEmail")" >> $GITHUB_ENV
      - name: Create control file
        run: |
          mkdir -p $GITHUB_WORKSPACE/pkg/DEBIAN
          {
          echo "Package: $PACKAGE_NAME"
          echo "Description: $DESCRIPTION"
          echo "Homepage: $URL"
          echo "Version: $VERSION"
          echo "Maintainer: $MAINTAINER <$MAINTAINER_EMAIL>"
          echo "Architecture: all"
          echo "Depends: python3, python3-gi, gir1.2-gtk-4.0, gir1.2-adw-1"
          } > $GITHUB_WORKSPACE/pkg/DEBIAN/control
      - name: Install files
        run: |
          install -Dm755 main.py "$GITHUB_WORKSPACE/pkg/usr/lib/shaweelTimer/main.py"
          install -Dm755 status.py "$GITHUB_WORKSPACE/pkg/usr/lib/shaweelTimer/status.py"
          install -Dm755 config.py "$GITHUB_WORKSPACE/pkg/usr/lib/shaweelTimer/config.py"
          install -Dm755 shaweeltimer "$GITHUB_WORKSPACE/pkg/usr/bin/shaweeltimer"
          install -Dm644 shaweelTimer.desktop "$GITHUB_WORKSPACE/pkg/usr/share/applications/shaweelTimer.desktop"
          install -Dm644 metadata.json "$GITHUB_WORKSPACE/pkg/usr/lib/shaweelTimer/metadata.json"
          ./generateVersionData.sh "Debian (.deb)" $VERSION ${{github.ref_name}} ${{github.run_number}}
          install -Dm644 versionData.json "$GITHUB_WORKSPACE/pkg/usr/lib/shaweelTimer/versionData.json"
          install -Dm644 assets/shaweelTimer.png "$GITHUB_WORKSPACE/pkg/usr/share/icons/hicolor/256x256/apps/shaweeltimer.png"
          
      - name: Build .deb file
        run: |
          dpkg-deb --build $GITHUB_WORKSPACE/pkg $GITHUB_WORKSPACE/shaweelTimer-${{github.ref_name}}-$VERSION.deb
      - name: Upload .deb file as artifact
        uses: actions/upload-artifact@v6
        with:
          name: shaweelTimerDebian-${{github.ref_name}}-${{env.VERSION}}
          path: ${{ github.workspace }}/shaweelTimer-${{github.ref_name}}-${{env.VERSION}}.deb
  buildRpm:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files from repository to workspace
        uses: actions/checkout@v6
      - name: Fetch metadata
        run: |
          fetchMetadataValue() {
            curl -s https://raw.githubusercontent.com/shaweel/shaweelTimer/refs/heads/${{ github.ref_name }}/metadata.json \
            | grep -o "\"$1\": *\"[^\"]*\"" \
            | sed 's/.*: *"\(.*\)"/\1/'
          }
          echo "PACKAGE_NAME=$(fetchMetadataValue "packageName")" >> $GITHUB_ENV
          echo "DESCRIPTION=$(fetchMetadataValue "description")" >> $GITHUB_ENV
          echo "VERSION=$(fetchMetadataValue "version")" >> $GITHUB_ENV
          echo "URL=$(fetchMetadataValue "url")" >> $GITHUB_ENV
          echo "MAINTAINER=$(fetchMetadataValue "maintainer")" >> $GITHUB_ENV
          echo "MAINTAINER_EMAIL=$(fetchMetadataValue "maintainerEmail")" >> $GITHUB_ENV
      - name: Create needed directories
        run: mkdir -p $GITHUB_WORKSPACE/rpm/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
      - name: Create rpm spec file
        run: |
          {
          echo "Name: $PACKAGE_NAME"
          echo "URL: $URL"
          echo "Version: $VERSION"
          echo "Release: 1%{?dist}"
          echo "Summary: $DESCRIPTION"
          echo "Packager: $MAINTAINER <$MAINTAINER_EMAIL>"
          echo "BuildArch: noarch"
          echo "License: GPL-3.0-or-later"
          echo "Requires: python3, python3-gobject, gtk4, libadwaita, libGLESv2.so.2"
          echo ""
          echo "%description"
          echo "$DESCRIPTION"
          echo ""
          echo "%install"
          echo "install -Dm755 $GITHUB_WORKSPACE/main.py %{buildroot}/usr/lib/shaweelTimer/main.py"
          echo "install -Dm755 $GITHUB_WORKSPACE/status.py %{buildroot}/usr/lib/shaweelTimer/status.py"
          echo "install -Dm755 $GITHUB_WORKSPACE/config.py %{buildroot}/usr/lib/shaweelTimer/config.py"
          echo "install -Dm755 $GITHUB_WORKSPACE/shaweeltimer %{buildroot}/usr/bin/shaweeltimer"
          echo "install -Dm755 $GITHUB_WORKSPACE/shaweelTimer.desktop %{buildroot}/usr/share/applications/shaweeltimer.desktop"
          echo "$GITHUB_WORKSPACE/generateVersionData.sh \"Fedora (.rpm)\" $VERSION ${{github.ref_name}} ${{github.run_number}}"
          echo "install -Dm644 ./versionData.json %{buildroot}/usr/lib/shaweelTimer/versionData.json"
          echo "install -Dm644 $GITHUB_WORKSPACE/metadata.json %{buildroot}/usr/lib/shaweelTimer/metadata.json"
          echo "install -Dm644 $GITHUB_WORKSPACE/assets/shaweelTimer.png %{buildroot}/usr/share/icons/hicolor/256x256/apps/shaweeltimer.png"
          echo ""
          echo "%files"
          echo "/usr/lib/shaweelTimer/*"
          echo "/usr/bin/shaweeltimer"
          echo "/usr/share/icons/hicolor/256x256/apps/shaweeltimer.png"
          echo "/usr/share/applications/shaweeltimer.desktop"
          } > $GITHUB_WORKSPACE/rpm/SPECS/shaweeltimer.spec
      - name: Build .rpm file
        run: |
          rpmbuild -bb --define "_topdir $GITHUB_WORKSPACE/rpm" $GITHUB_WORKSPACE/rpm/SPECS/shaweeltimer.spec
          mv $GITHUB_WORKSPACE/rpm/RPMS/noarch/*.rpm $GITHUB_WORKSPACE/shaweelTimer-${{github.ref_name}}-$VERSION.rpm
      - name: Upload .rpm file as artifact
        uses: actions/upload-artifact@v6
        with:
          name: shaweelTimerFedora-${{github.ref_name}}-${{env.VERSION}}
          path: ${{ github.workspace }}/shaweelTimer-${{github.ref_name}}-${{env.VERSION}}.rpm

  buildWindows:
    runs-on: windows-latest
    steps:
      - name: Copy files from repository to workspace
        uses: actions/checkout@v6
      - name: Fetch metadata
        shell: sh
        run: |
          fetchMetadataValue() {
            curl -s https://raw.githubusercontent.com/shaweel/shaweelTimer/refs/heads/${{ github.ref_name }}/metadata.json \
            | grep -o "\"$1\": *\"[^\"]*\"" \
            | sed 's/.*: *"\(.*\)"/\1/'
          }
          echo "PACKAGE_NAME=$(fetchMetadataValue "packageName")" >> $GITHUB_ENV
          echo "DESCRIPTION=$(fetchMetadataValue "description")" >> $GITHUB_ENV
          echo "VERSION=$(fetchMetadataValue "version")" >> $GITHUB_ENV
          echo "URL=$(fetchMetadataValue "url")" >> $GITHUB_ENV
          echo "MAINTAINER=$(fetchMetadataValue "maintainer")" >> $GITHUB_ENV
          echo "MAINTAINER_EMAIL=$(fetchMetadataValue "maintainerEmail")" >> $GITHUB_ENV
      - name: Install MSYS2 and build dependencies inside it
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-gobject
            mingw-w64-x86_64-python-cairo
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-adwaita-icon-theme
      - name: Install files
        shell: msys2 {0}
        run: |
          MINGW_WIN=$(cygpath -w $MINGW_PREFIX)
          ./generateVersionData.sh "Windows (.exe)" $VERSION ${{github.ref_name}} ${{github.run_number}}
          install -Dm644 versionData.json C:/ProgramData/shaweelTimer/versionData.json

      - name: Install PyInstaller
        shell: msys2 {0}
        run: pip install pyinstaller
      - name: Build .exe file
        shell: msys2 {0}
        run: |  
          MINGW_WIN=$(cygpath -w $MINGW_PREFIX)
          pyinstaller --onefile --windowed --collect-all gi \
          --add-data "$MINGW_WIN/lib/girepository-1.0;lib/girepository-1.0" \
          --add-data "$MINGW_WIN/share/glib-2.0/schemas;share/glib-2.0/schemas" \
           --add-data "$MINGW_WIN/share/icons;share/icons" \
          --add-data "$MINGW_WIN/lib/gdk-pixbuf-2.0;lib/gdk-pixbuf-2.0" \
          --add-data "assets/shaweelTimer.png;shaweelTimer" \
          --add-data "C:/ProgramData/shaweelTimer;shaweelTimer" \
          --icon assets/shaweelTimer.ico --clean --name shaweelTimer-${{github.ref_name}}-$VERSION main.py
      - name: Upload .exe file as artifact
        uses: actions/upload-artifact@v6
        with:
          name: shaweelTimerWindows-${{github.ref_name}}-${{env.VERSION}}
          path: dist/shaweelTimer-${{github.ref_name}}-${{env.VERSION}}.exe
